/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package e2e.test

import kotlin.test.Test
import kotlin.test.assertTrue

class MainTest {
    @Test
    fun mainTest() {
        val classUnderTest = Main()
        classUnderTest.test()
    }
}
